// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2f93AluMVBtb11H1R4U8X9ULlnROChaE',
    appId: '1:44035520025:web:18cd8cc44a2228d364dc88',
    messagingSenderId: '44035520025',
    projectId: 'monitoring-demo-dc294',
    authDomain: 'monitoring-demo-dc294.firebaseapp.com',
    storageBucket: 'monitoring-demo-dc294.firebasestorage.app',
    measurementId: 'G-LVRTZ7XKFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAINxey97jD1j4dvNW6H6-ExV7NJitqWqw',
    appId: '1:44035520025:android:0bc43eed8d5197df64dc88',
    messagingSenderId: '44035520025',
    projectId: 'monitoring-demo-dc294',
    storageBucket: 'monitoring-demo-dc294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS9aUXa7j51toa8iRAQdE2elTKg9RxzEY',
    appId: '1:44035520025:ios:c39ed34f6f2dd9ab64dc88',
    messagingSenderId: '44035520025',
    projectId: 'monitoring-demo-dc294',
    storageBucket: 'monitoring-demo-dc294.firebasestorage.app',
    iosBundleId: 'com.pmorales.monitoring.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS9aUXa7j51toa8iRAQdE2elTKg9RxzEY',
    appId: '1:44035520025:ios:f0b4880933b490e164dc88',
    messagingSenderId: '44035520025',
    projectId: 'monitoring-demo-dc294',
    storageBucket: 'monitoring-demo-dc294.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2f93AluMVBtb11H1R4U8X9ULlnROChaE',
    appId: '1:44035520025:web:43acaa46dc3aee5664dc88',
    messagingSenderId: '44035520025',
    projectId: 'monitoring-demo-dc294',
    authDomain: 'monitoring-demo-dc294.firebaseapp.com',
    storageBucket: 'monitoring-demo-dc294.firebasestorage.app',
    measurementId: 'G-1SEVQ5GRXH',
  );
}
